### ISSUE TITLE
Login Confusing

### ISSUE THREAD

**Issue by dhardenb** [cypherlh/Steel_Magic__Struggle_of_Factions#5]
When you come to the screen and hit "register" you get sent to a new screen with the captcha test. Then, after you pass the test, you go back to the first screen that looks the same. I hit register again thinking I maybe failed the captcha test and it registered a blank user name and password. :-)

Not really a bug per say, but a little confusing.

**Comment by cypherlh** [comment]
Hey Dave, does the login process seem any less confusing than it did last time you tried?

**Comment by cypherlh** [comment]
I'm going to mark this as closed
